# Generated by Django 5.0.4 on 2024-04-27 15:53

from django.db import migrations
import random

class Migration(migrations.Migration):

    def generate_data(apps, schema_editor):
        Channel = apps.get_model('main', 'Channel')
        Program = apps.get_model('main', 'Program')

        channels = 6

        for x in range(1, channels + 1):
            Channel.objects.create(title=f'Канал {x}')

        weekdays = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']

        for weekday in weekdays:
            for _ in range(1, 7 * channels + 1):
                Program.objects.create(
                    title=f'Програма {random.randint(1, 99)}',
                    start_time=f'{str(random.randint(1, 23)).zfill(2)}:00:00',
                    weekday=weekday,
                    channel_id=random.randint(1, channels)
                )
    
    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            generate_data,
        ),
    ]
